# Generated by Django 2.2.4 on 2019-08-16 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='nome')),
                ('email', models.EmailField(max_length=40, verbose_name='email')),
                ('telefone', models.CharField(max_length=15, verbose_name='telefone')),
                ('mensagem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=15, verbose_name='descriçao')),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=15, verbose_name='descriçao')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('nacionalidade', models.CharField(max_length=40, verbose_name='nacionalidade')),
                ('cpf', models.CharField(max_length=20, verbose_name='cpf')),
                ('celular', models.CharField(max_length=15, verbose_name='celular')),
                ('data_nascimento', models.DateField()),
                ('cep', models.CharField(max_length=20, verbose_name='cep')),
                ('rua', models.CharField(max_length=40, verbose_name='rua')),
                ('numero', models.IntegerField(verbose_name='numero')),
                ('complemento', models.CharField(max_length=60, null=True, verbose_name='complemento')),
                ('bairro', models.CharField(max_length=25, verbose_name='bairro')),
                ('matricula', models.CharField(max_length=15)),
                ('curso', models.CharField(max_length=20, verbose_name='curso')),
                ('periodo', models.IntegerField(verbose_name='periodo')),
                ('curriculo', models.FileField(upload_to='arquivos')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idades', to='core.Cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='core.Estado')),
            ],
        ),
    ]
