# Generated by Django 2.2.4 on 2019-08-16 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='curriculo',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='rua',
        ),
    ]
