# Generated by Django 2.2.4 on 2019-08-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190816_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(max_length=20, null=True, verbose_name='cpf'),
        ),
    ]
