# Generated by Django 2.2.4 on 2019-08-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_candidato_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='cep',
            field=models.CharField(max_length=20, null=True, verbose_name='cep'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='tipo_deficiencia',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
