# Generated by Django 2.2.4 on 2019-08-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190816_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='complemento',
            field=models.CharField(max_length=60, null=True, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='numero',
            field=models.IntegerField(null=True, verbose_name='numero'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='rua',
            field=models.CharField(max_length=40, null=True, verbose_name='rua'),
        ),
    ]
