# Generated by Django 2.2.4 on 2019-08-16 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190816_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='bairro',
            field=models.CharField(blank=True, max_length=25, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idades', to='core.Cidade'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='core.Estado'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='matricula',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='descricao',
            field=models.CharField(max_length=15, null=True, verbose_name='descriçao'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='descricao',
            field=models.CharField(max_length=15, null=True, verbose_name='descriçao'),
        ),
    ]
