# Generated by Django 2.2.4 on 2019-08-16 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190816_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='arquivo',
        ),
    ]
