# Generated by Django 2.2.4 on 2019-08-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_candidato_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='arquivo',
            field=models.FileField(null=True, upload_to='arquivos'),
        ),
    ]
