# Generated by Django 2.2.4 on 2019-08-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_candidato_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='cpf'),
        ),
    ]
