# Generated by Django 2.2.4 on 2019-08-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190816_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='rua',
            new_name='logradouro',
        ),
        migrations.AddField(
            model_name='candidato',
            name='deficiencia',
            field=models.CharField(max_length=2, null=True, verbose_name='deficiencia'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='estado_civil',
            field=models.CharField(max_length=15, null=True, verbose_name='estado_civil'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='genero',
            field=models.CharField(max_length=15, null=True, verbose_name='genero'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cep',
            field=models.CharField(max_length=10, null=True, verbose_name='cep'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cidade',
            field=models.CharField(max_length=30, null=True, verbose_name='idades'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='curso',
            field=models.CharField(max_length=30, null=True, verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='estado',
            field=models.CharField(max_length=3, null=True, verbose_name='estados'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='matricula',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='periodo',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='periodo'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='tipo_deficiencia',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
