# Generated by Django 2.2.4 on 2019-08-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_candidato_arquivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='celular',
            new_name='telefone',
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='cpf'),
        ),
    ]
