# Generated by Django 2.2.4 on 2019-08-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190818_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='arquivo',
            field=models.FileField(null=True, upload_to='arquivos'),
        ),
    ]
