# Generated by Django 2.2.4 on 2019-08-28 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190818_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='arquivo',
        ),
    ]
