# Generated by Django 2.2.4 on 2019-08-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_candidato_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='data_nascimento'),
        ),
    ]
