# Generated by Django 2.2.4 on 2019-08-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190828_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='data_nascimento',
        ),
    ]
