# Generated by Django 2.2.4 on 2019-08-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_candidato_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='arquivo',
            field=models.FileField(null=True, upload_to='arquivos'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='data_nascimento'),
        ),
    ]
