# Generated by Django 2.2.4 on 2019-08-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190828_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='deficiencia',
            field=models.CharField(max_length=5, null=True, verbose_name='deficiencia'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='estado',
            field=models.CharField(max_length=4, null=True, verbose_name='estados'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='periodo',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='periodo'),
        ),
    ]
